modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Joshcraft2002/Dumplings-Delight-Rewrapped/issues" #optional

[[mods]] #mandatory
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Joshcraft2002/Dumplings-Delight-Rewrapped/main/update.json"
logoFile="logo.png"
credits="FoggyHillSide as original mod author"
authors="${mod_authors}"
description='''${mod_description}'''
## Catalogue mod compatibility
itemIcon = "dumplings_delight:pork_celery_boiled_dumpling"
configBackground = "minecraft:textures/block/stripped_oak_log.png"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.4,)"
    ordering="AFTER"
    side="BOTH"
